### ISSUE TITLE
Windows install fails

### ISSUE THREAD

**Issue by metaclassing** [chef-cookbooks/php#123]
http://windows.php.net/downloads/releases/php-5.3.28-nts-Win32-VC9-x86.msi is the default windows installer URL, which can not be found. Install on windows servers with IIS does not appear to function currently.

I found a copy of the file and placed it in another URL which downloaded successfully, however the install still failed during msiexec. Not sure if x86 is mandatory or desired on server 2012r2 x64 arch.

Anybody use this cookbook to install a WIMP environment?

**Comment by Rockstar04** [comment]
It looks like MSI installers are no longer provided by Zend, and a zip of the php exe is the thing provided for Windows.

It looks like Windows support would have to be completely reworked to support "installing" from the zip files provided.

One quick thing you could do to install PHP 5.3 (not recommended since its not supported anymore) is to update the `['php']['windows']['msi_source']` to `http://windows.php.net/downloads/releases/php-5.3.28-nts-Win32-VC9-x86.msi`

**Comment by tas50** [comment]
This will be fixed with #149
