### ISSUE TITLE
Any plans to add support for PHP greater than 5.3 on Amazon Linux?

### ISSUE THREAD

**Issue by eric-tucker** [chef-cookbooks/php#166]
This cookbook is years old and still does not support installing from yum versions of php greater than 5.3 as all versions greater than 5.3 on Amazon Linux are labelled php54, php55, and php56.

This cookbook still relies on the platform family of rhel and version greater than or equal to 6 to install the package "php".

I honestly thought by now that someone might have complained about this.  I'm surprised. I started using Chef over 2 years ago, saw this cookbook, and could not use it THEN.  Disappointing to see it's still not useful on Amazon Linux.  :(

**Comment by tas50** [comment]
Amazon Linux is a bit tricky since our testing model uses kitchen-docker in Travis and figuring out exactly what date amazon makes the jumps in their packages can be "challenging" to say the least. We've done it in a lot of other cookbooks, but it is true that we're not doing a good job of supporting Amazon Linux here.  Let me fire up an Amazon box and see what it would take to clean up the code a bit.

Also we're going to rewrite this entire cookbook in the near future and hopefully eliminate some of the need for funky case statements deciding what packages to instal.

**Comment by tas50** [comment]
2411edf0c6e2d66ffd3c8deec5faae1985ef64b2 should resolve this.  Feel free to open this back up if there's anything else that needs to get fixed.
